version: '3.8'
services:
  node-api:
    container_name: node-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      .env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: node-db
